language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

deploy:
  provider: heroku
  api_key:
    secure: 241675c3-cfe8-4a8c-9db7-da19d33ca548
  app: campgrounds-heroku
  on:
    repo: abdulc9/webdev
