language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: CfsKrmB0/XVFxPzyWA2I1pJw5PntALkqWa4KeTdqgvCKVXZzuCXhxnXzO4Bjb1DTCbAYetgZSyag2BH/dV2g0chNIqG9e21NXI5636cpIxDv8JQgvWNDTe2BGiZoKButibGq4Gp4V+sSlWbMLyfT/l/nOjEqdGhUvADB8RacZA02QmPVY0xSLPcC/nq8qt53eCoH1cNXDZtsYbByySz8i+tWx2gp9yzZihlg2idj7y3g2cWmyoKqqZk7+na8733ibCSwx3/6JykvFoplq3e8XpV5EgsecvTdkgsdsaHAtc9hgASkHp4GgrilIIWkoSqGcYNH1fGlw2rD4r0OCt/sAuB8G1mIPWEGlNQB6yeten9Gk0vd63q+TkYHSkM7yfm6p9Y9gvA4S1T8FpDH93iDnlsNDd9VWz9bagN1wNht/djtjyouQOjvxLA+LBa0S1YHsIF+H1aoVRHCygErk1ByGCe1RabfWzkXINere/uzLAw1Ru9/qt8uXbYjVGQP6kvSl/DdniJ+6HOv1EzWKnFINAEy95QAr5OE3b3P3o/zdF2xjUoEmsw3vjY8BjGjbiKJoFa4RF46xapml6s0hjSGnlYqxih4woPKN7oB54sByXYkxSxYaIscen9sDnrAQfMyNReOBb5Ub0tch3Xg9LHB0M6S8rlk8DUec2gPKDj6OqQ=
  app: campgrounds-heroku
  on:
    repo: abdulc9/webdev
